# Default values for argo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argo-cd:
  crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: false
    # -- Annotations to be added to all CRDs
    annotations: {}

  configs:
    secret:
      argocdServerAdminPassword: $2a$12$A9F8xmpkoQbN/y970jJ5CenHGYYJ2LG7PfbmlGnDwHyXiDlupygiS 
