# Default values for monitoring 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  image:
    repository: angelfoxxu/speed-grafana
    tag: 0.0.4
  adminPassword: password
